#!/usr/bin/env python3
"""Flatten the skill into a single system prompt for platforms without skills.

The skill relies on progressive disclosure: SKILL.md loads on trigger, the
reference files load only when read. Platforms that have no skill mechanism
(ChatGPT, Gemini, local models, most third-party clients) need everything in one
block instead. This produces that block.

Usage:
    python scripts/build_system_prompt.py                    # everything
    python scripts/build_system_prompt.py --provider openai  # drop foreign sections
    python scripts/build_system_prompt.py --core             # SKILL.md only
    python scripts/build_system_prompt.py -o prompt.md       # write to file
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ORDER = [
    "artifact-routing.md",
    "model-classes.md",
    "delivery-mechanics.md",
    "agentic-prompts.md",
    "examples.md",
    "self-and-subagents.md",
    "evaluation.md",
]
# Sections tagged for one provider are dropped when building for another.
TAG_RE = re.compile(r"^##\s+(.*?)\s*\[([^\]]+)\]\s*$", re.M)


def strip_frontmatter(text):
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4 :].lstrip("\n")
    return text


def filter_by_provider(text, provider):
    """Drop level-2 sections tagged for a different provider."""
    if provider in (None, "all"):
        return TAG_RE.sub(lambda m: f"## {m.group(1)}", text)
    out, drop = [], False
    for line in text.splitlines(keepends=True):
        m = TAG_RE.match(line.rstrip("\n") + "\n") if line.startswith("## ") else None
        if line.startswith("## "):
            if m:
                tags = m.group(2).lower()
                foreign = "anthropic" in tags and provider != "anthropic"
                universal = "universal" in tags or "principle universal" in tags
                drop = foreign and not universal
                line = f"## {m.group(1)}\n"
            else:
                drop = False
        if not drop:
            out.append(line)
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--provider", choices=["all", "anthropic", "openai", "google", "open-weights"],
                    default="all", help="drop sections that only apply elsewhere")
    ap.add_argument("--core", action="store_true", help="SKILL.md only, no references")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    args = ap.parse_args()

    skill = ROOT / "SKILL.md"
    if not skill.exists():
        sys.exit(f"SKILL.md not found at {skill}")

    parts = [
        "<!-- Generated by scripts/build_system_prompt.py. Edit the skill, not this file. -->",
        f"<!-- provider profile: {args.provider} -->",
        "",
        strip_frontmatter(skill.read_text()).strip(),
    ]

    if not args.core:
        for name in ORDER:
            path = ROOT / "references" / name
            if not path.exists():
                print(f"warning: missing {name}", file=sys.stderr)
                continue
            body = filter_by_provider(path.read_text().strip(), args.provider)
            parts += ["", "---", "", body.strip()]

    # The skill body points at reference files that no longer exist standalone.
    text = "\n".join(parts)
    text = re.sub(r"`references/([a-z-]+)\.md`", r"the section on \1 below", text)

    if args.output:
        pathlib.Path(args.output).write_text(text + "\n")
        words = len(text.split())
        print(f"wrote {args.output}: {len(text)} chars, ~{words} words, ~{int(words*1.4)} tokens")
    else:
        print(text)


if __name__ == "__main__":
    main()
